kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet publish -c Release -o ./app

  - name: docker-build
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.dev.ems-app.ru/learn-drone
      registry: registry.dev.ems-app.ru
      dockerfile: LearnDrone/Dockerfile.Drone

  - name: deploy
    image: docker:stable
    environment:
      INPUT_REMOTE_HOST: 
        from_secret: ssh-host
      INPUT_SSH_PRIVATE_KEY:
        from_secret: ssh-private-key
      INPUT_SSH_PUBLIC_KEY:
        from_secret: ssh-public-key
    commands:
      -  chmod +x ./deploy.sh
      -  echo $REGISTRY_USERNAME
      -  docker login registry.dev.ems-app.ru -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
      - ./deploy.sh learn-drone
    secrets: [registry_username, registry_password]
    