kind: pipeline
type: docker
name: default
environment:
  DOCKERFILE:
    from_secret: dockerfile
  IMAGE:
    from_secret: image
  REGISTRY:
    from_secret: registry
  REGISTRY_USERNAME:
    from_secret: registry_username
  REGISTRY_PASSWORD:
    from_secret: registry_password
  INPUT_REMOTE_HOST:
    from_secret: ssh_host
  INPUT_SSH_PRIVATE_KEY:
    from_secret: ssh_private_key
  INPUT_SSH_PUBLIC_KEY:
    from_secret: ssh_public_key
    
    
steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet publish -c Release -o ./app

  - name: docker-build
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: ${REGISTRY}/${IMAGE}
      registry: ${REGISTRY}
      dockerfile:
        from_secret: dockerfile

  - name: deploy
    image: docker:stable
    environment:
    
    
    commands:
      - chmod +x ./deploy.sh
      - echo $REGISTRY_USERNAME
      - docker login $REGISTRY -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
      - ./deploy.sh learn-drone
    