kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet publish -c Release -o /app

  - name: docker-build
    image: plugins/docker
    settings:
      username: admin
      password: Warnet77
      repo: registry.dev.gbms.site/learn-drone
      registry: registry.dev.gbms.site
      dockerfile: LearnDrone/Dockerfile.Drone