kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet publish -c Release -o ./app

  - name: docker-build
    image: plugins/docker
    settings:
      username:
        from_secret: registry-username
      password: 
        from_secret: registry-password
      repo: registry.dev.ems-app.ru/learn-drone
      registry: registry.dev.ems-app.ru
      dockerfile: LearnDrone/Dockerfile.Drone